//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTester.Echo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleTester.Echo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;CompletionText&quot;:&quot;Aggregate&quot;,&quot;Description&quot;:&quot;&quot;,&quot;DisplayText&quot;:&quot;Aggregate(Func&lt;char, char, char&gt; func)&quot;,&quot;RequiredNamespaceImport&quot;:null,&quot;MethodHeader&quot;:null,&quot;ReturnType&quot;:&quot;char&quot;,&quot;Snippet&quot;:null,&quot;Kind&quot;:&quot;Method&quot;,&quot;IsSuggestionMode&quot;:false},{&quot;CompletionText&quot;:&quot;Aggregate&quot;,&quot;Description&quot;:&quot;&quot;,&quot;DisplayText&quot;:&quot;Aggregate(TAccumulate seed, Func&lt;TAccumulate, char, TAccumulate&gt; func)&quot;,&quot;RequiredNamespaceImport&quot;:null,&quot;MethodHeader&quot;:null,&quot;ReturnType&quot;:&quot;TAccumulate&quot;,&quot;Snippet&quot;:null,&quot;Kind&quot;:&quot;Method&quot;,&quot;IsSuggestionMode&quot;:false},{&quot;Completion [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoCompleteResponse {
            get {
                return ResourceManager.GetString("AutoCompleteResponse", resourceCulture);
            }
        }
    }
}
